# Fuel Price UK

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as np
import warnings
warnings.filterwarnings('ignore') # HIdes harmless warning clutter

In [4]:
#Load the dataset

data = pd.read_csv("../data/price_history.csv")

In [6]:
#checking row and columns
data.shape

(229232, 6)

In [9]:
#Checking the column names
data.columns

Index(['id', 'node_id', 'fuel_type', 'price_pence', 'recorded_at',
       'source_updated_at'],
      dtype='object')

In [10]:
# Checking the first 5 data
data.head()

,id,node_id,fuel_type,price_pence,recorded_at,source_updated_at
0,1,4882e3fee979cfefa29a8777ce57ca0ecea27b4f12ba7f...,E10,126.0,2026-02-07T21:40:01.511Z,2026-02-06T12:46:05.000Z
1,2,4882e3fee979cfefa29a8777ce57ca0ecea27b4f12ba7f...,B7_STANDARD,135.0,2026-02-07T21:40:01.511Z,2026-02-06T12:46:05.000Z
2,3,b739362af81acc9fec9eda6f155348125fa2d5c1772c96...,E10,127.0,2026-02-07T21:40:01.511Z,2026-02-01T11:04:45.000Z
3,4,b739362af81acc9fec9eda6f155348125fa2d5c1772c96...,B7_STANDARD,138.0,2026-02-07T21:40:01.511Z,2026-02-01T11:04:45.000Z
4,5,ae5b2f8f6979b8b2460ff52f85619dd0dfc6a10bc98ca1...,E5,146.0,2026-02-07T21:40:01.511Z,2026-02-06T13:57:50.000Z

In [11]:
#chekcing the bottom 5 data
data.tail()

,id,node_id,fuel_type,price_pence,recorded_at,source_updated_at
229227,229772,b4d4eaa2aaf0a5617a5e4d467bd65513bde7b4ccbc7c0f...,E10,149.9,2026-03-22T23:28:06.115Z,2026-03-22T23:25:29.000Z
229228,229773,b4d4eaa2aaf0a5617a5e4d467bd65513bde7b4ccbc7c0f...,B7_STANDARD,173.9,2026-03-22T23:28:06.115Z,2026-03-22T23:25:29.000Z
229229,229774,b4d4eaa2aaf0a5617a5e4d467bd65513bde7b4ccbc7c0f...,B7_PREMIUM,189.9,2026-03-22T23:28:06.115Z,2026-03-22T23:25:29.000Z
229230,229775,62934f040255eac8763683d845aa0daa974bba7018a1b4...,E10,146.9,2026-03-22T23:28:06.115Z,2026-03-22T23:26:45.000Z
229231,229776,62934f040255eac8763683d845aa0daa974bba7018a1b4...,B7_STANDARD,169.9,2026-03-22T23:28:06.115Z,2026-03-22T23:26:45.000Z

In [12]:
# Understanding the data type
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229232 entries, 0 to 229231
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 229232 non-null  int64
 1   node_id            229232 non-null  object
 2   fuel_type          229232 non-null  object
 3   price_pence        229232 non-null  float64
 4   recorded_at        229232 non-null  object
 5   source_updated_at  229232 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 10.5+ MB

Here, the recorded_at and source_updated_at should be Date and time not object

In [13]:
# Fixing the date column in recorded_at

data['recorded_at'] = pd.to_datetime(data['recorded_at'])
data['source_updated_at'] = pd.to_datetime(data['source_updated_at'])

# Extracting the useful data type only 
data['date'] = data['recorded_at'].dt.date
data['hour'] = data['recorded_at'].dt.hour
data['day_of_week'] = data['recorded_at'].dt.day_name()
data['week'] = data['recorded_at'].dt.isocalendar().week

In [14]:
print("Date range of this dataset")
print(f"From:{data['recorded_at'].min()}")
print(f"From:{data['recorded_at'].max()}")

Date range of this dataset
From:2026-02-07 21:40:01.511000+00:00
From:2026-03-22 23:28:06.115000+00:00

This data covers roughly 44 days about 6 weeks of UK fuel prices across 7,442 stations.

In [15]:
# Check data quality
data.isnull().sum()

id                   0
node_id              0
fuel_type            0
price_pence          0
recorded_at          0
source_updated_at    0
date                 0
hour                 0
day_of_week          0
week                 0
dtype: int64

In [17]:
#Checking the price statistics
data['price_pence'].describe()

count    229232.000000
mean        153.733196
std          41.009238
min           0.000000
25%         140.000000
50%         149.900000
75%         163.900000
max        1949.000000
Name: price_pence, dtype: float64

In [ ]:
print("\n=== SUSPICIOUS PRICES ===")

print(f"Prices equal to 0p:{(data['price_pence'] == 0).sum()}")
print(f"Prices below 50p:{(data['price_pence'] < 50).sum()}")
print(f"Prices above 500p:{(data['price_pence'] > 500).sum()}")

=== SUSPICIOUS PRICES ===
Prices equal to 0:2
Prices below 50p:494
Prices above 500p:327

In [19]:
print(data['fuel_type'].value_counts())

fuel_type
B7_STANDARD    80203
E10            68957
E5             44064
B7_PREMIUM     35334
B10              353
HVO              321
Name: count, dtype: int64