# Fuel Price UK

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as np
import warnings
warnings.filterwarnings('ignore') # HIdes harmless warning clutter

In [2]:
#Load the dataset

data = pd.read_csv("../data/price_history.csv")

In [3]:
#checking row and columns
data.shape

(229232, 6)

In [4]:
#Checking the column names
data.columns

Index(['id', 'node_id', 'fuel_type', 'price_pence', 'recorded_at',
       'source_updated_at'],
      dtype='object')

In [5]:
# Checking the first 5 data
data.head()

,id,node_id,fuel_type,price_pence,recorded_at,source_updated_at
0,1,4882e3fee979cfefa29a8777ce57ca0ecea27b4f12ba7f...,E10,126.0,2026-02-07T21:40:01.511Z,2026-02-06T12:46:05.000Z
1,2,4882e3fee979cfefa29a8777ce57ca0ecea27b4f12ba7f...,B7_STANDARD,135.0,2026-02-07T21:40:01.511Z,2026-02-06T12:46:05.000Z
2,3,b739362af81acc9fec9eda6f155348125fa2d5c1772c96...,E10,127.0,2026-02-07T21:40:01.511Z,2026-02-01T11:04:45.000Z
3,4,b739362af81acc9fec9eda6f155348125fa2d5c1772c96...,B7_STANDARD,138.0,2026-02-07T21:40:01.511Z,2026-02-01T11:04:45.000Z
4,5,ae5b2f8f6979b8b2460ff52f85619dd0dfc6a10bc98ca1...,E5,146.0,2026-02-07T21:40:01.511Z,2026-02-06T13:57:50.000Z

In [6]:
#chekcing the bottom 5 data
data.tail()

,id,node_id,fuel_type,price_pence,recorded_at,source_updated_at
229227,229772,b4d4eaa2aaf0a5617a5e4d467bd65513bde7b4ccbc7c0f...,E10,149.9,2026-03-22T23:28:06.115Z,2026-03-22T23:25:29.000Z
229228,229773,b4d4eaa2aaf0a5617a5e4d467bd65513bde7b4ccbc7c0f...,B7_STANDARD,173.9,2026-03-22T23:28:06.115Z,2026-03-22T23:25:29.000Z
229229,229774,b4d4eaa2aaf0a5617a5e4d467bd65513bde7b4ccbc7c0f...,B7_PREMIUM,189.9,2026-03-22T23:28:06.115Z,2026-03-22T23:25:29.000Z
229230,229775,62934f040255eac8763683d845aa0daa974bba7018a1b4...,E10,146.9,2026-03-22T23:28:06.115Z,2026-03-22T23:26:45.000Z
229231,229776,62934f040255eac8763683d845aa0daa974bba7018a1b4...,B7_STANDARD,169.9,2026-03-22T23:28:06.115Z,2026-03-22T23:26:45.000Z

In [7]:
# Understanding the data type
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229232 entries, 0 to 229231
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 229232 non-null  int64
 1   node_id            229232 non-null  object
 2   fuel_type          229232 non-null  object
 3   price_pence        229232 non-null  float64
 4   recorded_at        229232 non-null  object
 5   source_updated_at  229232 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 10.5+ MB

Here, the recorded_at and source_updated_at should be Date and time not object

In [8]:
# Fixing the date column in recorded_at

data['recorded_at'] = pd.to_datetime(data['recorded_at'])
data['source_updated_at'] = pd.to_datetime(data['source_updated_at'])

# Extracting the useful data type only 
data['date'] = data['recorded_at'].dt.date
data['hour'] = data['recorded_at'].dt.hour
data['day_of_week'] = data['recorded_at'].dt.day_name()
data['week'] = data['recorded_at'].dt.isocalendar().week

In [9]:
print("Date range of this dataset")
print(f"From:{data['recorded_at'].min()}")
print(f"From:{data['recorded_at'].max()}")

Date range of this dataset
From:2026-02-07 21:40:01.511000+00:00
From:2026-03-22 23:28:06.115000+00:00

This data covers roughly 44 days about 6 weeks of UK fuel prices across 7,442 stations.

In [10]:
# Check data quality
data.isnull().sum()

id                   0
node_id              0
fuel_type            0
price_pence          0
recorded_at          0
source_updated_at    0
date                 0
hour                 0
day_of_week          0
week                 0
dtype: int64

In [11]:
#Checking the price statistics
data['price_pence'].describe()

count    229232.000000
mean        153.733196
std          41.009238
min           0.000000
25%         140.000000
50%         149.900000
75%         163.900000
max        1949.000000
Name: price_pence, dtype: float64

1949 penny is so extreme it drags the mean upward for that fuel type. which cause wrong insight

In [12]:
print("\n- SUSPICIOUS PRICES -")
print(f"Prices equal to 0 penny :{(data['price_pence'] == 0).sum()}")
print(f"Prices below 50 penny :{(data['price_pence'] < 50).sum()}")
print(f"Prices above 500 penny :{(data['price_pence'] > 500).sum()}")

- SUSPICIOUS PRICES -
Prices equal to 0 penny :2
Prices below 50 penny :494
Prices above 500 penny :327

- When Fuel Price is at 0 Penny

 A fuel price of zero penny is physically impossible. You cannot buy fuel for free. These are almost certainly one of two things: a system error where the station's pump failed to transmit a price, or a placeholder value inserted when no data was available.

- When Fule Price is at 50 penny

UK fuel has never been below 50p per litre in modern history. So these 494 records are not real prices. They likely come from stations entering prices in the wrong unit (pounds instead of pence), test entries from engineers setting up new stations, or corrupted transmissions.

- When Fule Price is at 500 Penny

500p per litre would be £5.00 per litre — roughly 3x the real price. These are the opposite problem: values that are wildly too high. Same causes — unit errors, data corruption, or test data that never got cleaned out of the production system.

In [13]:
# Removing the bad data 

data_clean = data[data['price_pence']>=50 & (data['price_pence']<=400)].copy()
removed = len(data)-len(data_clean)

print(f"ORiginal rows:{len(data):,}")
print(f"Removed Rows:{removed:,}({removed/len(data)*100:.2f}% of the data)")
print(f"Clean rows:{len(data_clean):,}")
print(f"\nPrice range after cleaning:")
print(f"  Min: {data_clean['price_pence'].min():.1f}p")
print(f"  Max: {data_clean['price_pence'].max():.1f}p")
print(f"  Avg: {data_clean['price_pence'].mean():.1f}p")

ORiginal rows:229,232
Removed Rows:0(0.00% of the data)
Clean rows:229,232

Price range after cleaning:
  Min: 0.0p
  Max: 1949.0p
  Avg: 153.7p

why 50p and 400p > because real UK fuel prices in early 2026 sit in that band . anything price beside that are consider as data entry mistake

In [14]:
# Cell 8 - Average price by fuel type
avg_by_fuel = data_clean.groupby('fuel_type')['price_pence'].agg(
     count='count',
     mean_price='mean',
     min_price='min',
     max_price='max'
).round(2).sort_values('mean_price', ascending=False)

print("AVERAGE PRICE BY FUEL TYPE (pence per litre)\n")
print(avg_by_fuel.to_string())

AVERAGE PRICE BY FUEL TYPE (pence per litre)

             count  mean_price  min_price  max_price
fuel_type
B7_PREMIUM   35334      173.94       1.00     1949.0
HVO            321      165.61      11.61      444.0
E5           44064      157.48       0.00     1709.0
B7_STANDARD  80203      154.35       1.00     1777.0
B10            353      142.37       1.00      921.0
E10          68957      140.27       1.00     1479.0

max price can't be that high for all the fule price . it might be data entry mistake .

In [15]:
# Checking the exterme price properly 
print("Heighest prices in dataset \n")
print(data.nlargest(10,'price_pence')[['node_id','fuel_type','price_pence','recorded_at']])

Heighest prices in dataset

                                                  node_id    fuel_type  \
130059  7e54b71d4fc9e3cd9d0f87e6ff69184eb7001a3de05c08...   B7_PREMIUM
212282  0c5dee22ecf242d1027b6118eac744e01755e080df95a1...  B7_STANDARD
169547  3631dbafa225c68604b9d288cf0b44e26a14912ce713d8...  B7_STANDARD
210995  91909366652067d23e82c14e9d55924d3ddf1549434440...  B7_STANDARD
130056  7e54b71d4fc9e3cd9d0f87e6ff69184eb7001a3de05c08...           E5
3311    24c76ae2c22792c298a81faeccbf2874cf2e9549135fcf...           E5
130058  7e54b71d4fc9e3cd9d0f87e6ff69184eb7001a3de05c08...  B7_STANDARD
137760  fa083c8f11b40cbf72156baaa440be52c841e40b51a637...  B7_STANDARD
186125  d1496354a7989d8aaf8bc0dbe3cc3331c4d677dcd85544...  B7_STANDARD
2919    05c79b55166e623e0f9f4de82fc6f00dd31329fc85a5ba...  B7_STANDARD

        price_pence                      recorded_at
130059       1949.0 2026-03-09 12:48:07.713000+00:00
212282       1777.0 2026-03-20 18:12:06.829000+00:00
169547       1749.0 2026-03-16 07:16:01.225000+00:00
210995       1749.0 2026-03-20 16:32:23.705000+00:00
130056       1709.0 2026-03-09 12:48:07.713000+00:00
3311         1699.0 2026-02-07 21:40:01.860000+00:00
130058       1699.0 2026-03-09 12:48:07.713000+00:00
137760       1669.0 2026-03-10 08:40:07.541000+00:00
186125       1647.9 2026-03-18 07:36:01.332000+00:00
2919         1599.0 2026-02-07 21:40:01.775000+00:00

In [16]:
#chekcing the exterme records per fule type only 

print("Exterme recoreds per fule type\n ")
extreme_high = data[data['price_pence']>500]
print(extreme_high.groupby('fuel_type')['price_pence'].agg(['count','mean','max']))

Exterme recoreds per fule type

             count         mean     max
fuel_type
B10              2   722.450000   921.0
B7_PREMIUM      15  1285.386667  1949.0
B7_STANDARD     44  1352.287727  1777.0
E10            137  1062.823358  1479.0
E5             129  1063.530233  1709.0

In [17]:
# chekcing the price records per fule type below 50 penny 
print("records per fule type(belwo 50 penny)")
exterme_low = data[data['price_pence']<50]
print(exterme_low.groupby('fuel_type')['price_pence'].agg(['count','mean','max']))

records per fule type(belwo 50 penny)
             count       mean    max
fuel_type
B10             45  17.205556  31.31
B7_PREMIUM      67   3.970746  19.30
B7_STANDARD    135   7.428667  41.41
E10            136   3.746397  39.90
E5              97   7.590000  21.21
HVO             14  17.181429  17.61

In [18]:
#Does same stations have multiple bad price?

print("do same station have multiple bad prices ")
bad_stations = data[data['price_pence']>500]['node_id'].value_counts().head(10)
print(bad_stations)

do same station have multiple bad prices
node_id
c9aa1695a016aa511c09299537f3c6536c428a1958eacaa21f2b545f455ecdb5    215
0eab9305ef5cfedf81d5b430c2050f50882997a00abc926d11a73ea36e5fe398      6
eb2a4ec0d0d85fbe3f6ea05566415571be7274212e00e16c2d003239e7930cf2      4
32e5e276d604141ace5e2af9358d1ba0d16cf0d31566f0e3e86c4fafb82b9c3e      4
9a8f20268e424c379929cbb3cf83925a2ab1b7dda461795f46a164192fd576aa      4
fdf4974536725227197fa9209fcfc82f234cfe342613b63cf72a100ec1dec152      4
523e6288311b2a2437084e803bd869932ba9969c7bcacf4aa11bee2e98f630a9      4
3c8b86979ee1c44d3b365287150ed428293c2190f349b9af6a4f595bcfe1dc95      4
8cc27e4c09366d7f6fc648c6c6d4eda8e069a70254c6687b291959417f57412d      4
7e54b71d4fc9e3cd9d0f87e6ff69184eb7001a3de05c085565c92028a6f368ef      4
Name: count, dtype: int64

one station has 215 bad price records all by itself. every other station has only 4 - 6 . that single staion account tha more than 65% of all bad high price data out of 327 set. this might not be a random data entry mistake. it might be the cause of broken entyr sensor at that specifc staition that has been consistently transmitting garbage price .

In [25]:
# Deep dive into the problem station 

problem_station = 'c9aa1695a016aa511c09299537f3c6536c428a1958eacaa21f2b545f455ecdb5'

station_data = data[data['node_id']==problem_station]
print(f"total records for this stations: {len(station_data)}")
print(f"bad records (> 500penny):{len(station_data[station_data['price_pence']>500])}") # 500 penny vanda dheari liney petrol ko 
print(f"Good records (< 500penny):{len(station_data[station_data['price_pence']<500])}") # 500 penny vanda kaam liney

total records for this stations: 432
bad records (> 500penny):215
Good records (< 500penny):217

In [ ]:
#Checking the fuel type which it sellls
station_data['fuel_type'].value_counts() #high price ma petrol dine station ko type of fuel

fuel_type
E5             216
E10            213
B7_STANDARD      3
Name: count, dtype: int64

In [27]:
# Sample of bad prices 
bad_price = station_data[station_data['price_pence']>500][['fuel_type','price_pence','recorded_at']]
print(bad_price.sort_values('recorded_at').head(15))

      fuel_type  price_pence                      recorded_at
8506         E5       1000.0 2026-02-07 21:40:02.318000+00:00
8507        E10       1000.0 2026-02-07 21:40:02.318000+00:00
28018        E5       1000.0 2026-02-17 08:10:32.378000+00:00
28062        E5       1000.0 2026-02-17 08:57:03.384000+00:00
28078       E10       1000.0 2026-02-17 09:10:02.240000+00:00
28380        E5       1000.0 2026-02-17 11:52:34.734000+00:00
28473       E10       1000.0 2026-02-17 12:16:38.550000+00:00
28599        E5       1000.0 2026-02-17 12:40:53.969000+00:00
28614       E10       1000.0 2026-02-17 12:44:15.513000+00:00
28700        E5       1000.0 2026-02-17 13:25:11.607000+00:00
28778       E10       1000.0 2026-02-17 14:40:38.695000+00:00
29279        E5       1000.0 2026-02-17 17:53:07.771000+00:00
29576       E10       1000.0 2026-02-18 08:49:01.847000+00:00
29603        E5       1000.0 2026-02-18 09:52:08.104000+00:00
29751       E10       1000.0 2026-02-18 12:00:50.487000+00:00

In [29]:
#Sample of good price 
good_price = station_data[station_data['price_pence']<500][['fuel_type','price_pence','recorded_at']]
print(good_price.sort_values('recorded_at').head(15))

      fuel_type  price_pence                      recorded_at
27920        E5        124.0 2026-02-17 07:24:26.321000+00:00
28045        E5        124.0 2026-02-17 08:26:43.333000+00:00
28063       E10        138.0 2026-02-17 08:57:03.384000+00:00
28089        E5        124.0 2026-02-17 09:12:14.102000+00:00
28424       E10        138.0 2026-02-17 12:08:26.399000+00:00
28571        E5        124.0 2026-02-17 12:32:24.365000+00:00
28600       E10        138.0 2026-02-17 12:40:53.969000+00:00
28666        E5        124.0 2026-02-17 13:08:41.712000+00:00
28667       E10        138.0 2026-02-17 13:08:41.712000+00:00
29228        E5        124.0 2026-02-17 16:48:02.435000+00:00
29229       E10        138.0 2026-02-17 16:48:02.435000+00:00
29300        E5        124.0 2026-02-17 18:56:08.722000+00:00
29604       E10        138.0 2026-02-18 09:52:08.104000+00:00
29750        E5        124.0 2026-02-18 12:00:50.487000+00:00
29906       E10        138.0 2026-02-18 14:08:19.627000+00:00

In [31]:
#chekcing the bad prices happen at a specific time period bela 
station_data_copy = station_data.copy()
station_data_copy['is_bad'] = station_data_copy['price_pence'] >500
print(station_data_copy.groupby('is_bad')['recorded_at'].agg(['min','max']))

                                    min                              max
is_bad
False  2026-02-17 07:24:26.321000+00:00 2026-03-22 09:48:04.096000+00:00
True   2026-02-07 21:40:02.318000+00:00 2026-03-20 15:56:13.631000+00:00

so, bad priceing was started form feb 7 and good price started from feb 17 after 10 days only . this station was transmitting bad dataq from day one . then at some point started sending some good prices too .

In [32]:
# checking the cause and history over time 

problem_station = 'c9aa1695a016aa511c09299537f3c6536c428a1958eacaa21f2b545f455ecdb5'
station_data = data[data['node_id']==problem_station]
station_data = station_data.sort_values('recorded_at')
print(station_data[['fuel_type','price_pence','recorded_at']].to_string())

          fuel_type  price_pence                      recorded_at
8506             E5       1000.0 2026-02-07 21:40:02.318000+00:00
8507            E10       1000.0 2026-02-07 21:40:02.318000+00:00
27920            E5        124.0 2026-02-17 07:24:26.321000+00:00
28018            E5       1000.0 2026-02-17 08:10:32.378000+00:00
28045            E5        124.0 2026-02-17 08:26:43.333000+00:00
28062            E5       1000.0 2026-02-17 08:57:03.384000+00:00
28063           E10        138.0 2026-02-17 08:57:03.384000+00:00
28078           E10       1000.0 2026-02-17 09:10:02.240000+00:00
28089            E5        124.0 2026-02-17 09:12:14.102000+00:00
28380            E5       1000.0 2026-02-17 11:52:34.734000+00:00
28424           E10        138.0 2026-02-17 12:08:26.399000+00:00
28473           E10       1000.0 2026-02-17 12:16:38.550000+00:00
28571            E5        124.0 2026-02-17 12:32:24.365000+00:00
28599            E5       1000.0 2026-02-17 12:40:53.969000+00:00
28600           E10        138.0 2026-02-17 12:40:53.969000+00:00
28614           E10       1000.0 2026-02-17 12:44:15.513000+00:00
28666            E5        124.0 2026-02-17 13:08:41.712000+00:00
28667           E10        138.0 2026-02-17 13:08:41.712000+00:00
28700            E5       1000.0 2026-02-17 13:25:11.607000+00:00
28778           E10       1000.0 2026-02-17 14:40:38.695000+00:00
29228            E5        124.0 2026-02-17 16:48:02.435000+00:00
29229           E10        138.0 2026-02-17 16:48:02.435000+00:00
29279            E5       1000.0 2026-02-17 17:53:07.771000+00:00
29300            E5        124.0 2026-02-17 18:56:08.722000+00:00
29576           E10       1000.0 2026-02-18 08:49:01.847000+00:00
29604           E10        138.0 2026-02-18 09:52:08.104000+00:00
29603            E5       1000.0 2026-02-18 09:52:08.104000+00:00
29750            E5        124.0 2026-02-18 12:00:50.487000+00:00
29751           E10       1000.0 2026-02-18 12:00:50.487000+00:00
29906           E10        138.0 2026-02-18 14:08:19.627000+00:00
30010            E5       1000.0 2026-02-18 15:12:02.567000+00:00
30180            E5        124.0 2026-02-18 16:17:15.896000+00:00
30237           E10       1000.0 2026-02-18 18:25:34.226000+00:00
30242            E5       1000.0 2026-02-18 19:29:09.724000+00:00
30384           E10        138.0 2026-02-18 22:40:25.576000+00:00
30485            E5        124.0 2026-02-19 06:08:10.181000+00:00
30568            E5       1000.0 2026-02-19 08:17:27.260000+00:00
30635            E5        124.0 2026-02-19 10:14:20.452000+00:00
30787           E10       1000.0 2026-02-19 11:16:40.950000+00:00
30786            E5       1000.0 2026-02-19 11:16:40.950000+00:00
30896            E5        124.0 2026-02-19 12:56:04.336000+00:00
30897           E10        138.0 2026-02-19 12:56:04.336000+00:00
30917            E5       1000.0 2026-02-19 13:25:12.799000+00:00
30918           E10       1000.0 2026-02-19 13:25:12.799000+00:00
31138           E10        138.0 2026-02-19 14:28:42.941000+00:00
31396            E5        124.0 2026-02-19 15:32:48.220000+00:00
31456            E5       1000.0 2026-02-19 16:36:28.841000+00:00
31742            E5        124.0 2026-02-19 23:01:19.320000+00:00
31926            E5       1000.0 2026-02-20 06:29:14.965000+00:00
31927           E10       1000.0 2026-02-20 06:29:14.965000+00:00
31951           E10        138.0 2026-02-20 07:16:02.967000+00:00
31950            E5        124.0 2026-02-20 07:16:02.967000+00:00
32047            E5       1000.0 2026-02-20 08:36:20.612000+00:00
32111           E10       1000.0 2026-02-20 09:40:02.450000+00:00
32250            E5        124.0 2026-02-20 10:44:21.191000+00:00
32442            E5       1000.0 2026-02-20 12:52:02.764000+00:00
32557            E5        124.0 2026-02-20 13:56:20.650000+00:00
32568           E10        138.0 2026-02-20 14:09:56.725000+00:00
32977            E5       1000.0 2026-02-20 16:09:26.788000+00:00
32978           E10       1000.0 2026-02-20 16:09:26.788000+00:00
33062           E10        138.0 2026-02-20 17:12:20.527000+00:00
33256            E5        124.0 2026-02-20 22:33:02.084000+00:00
33347            E5       1000.0 2026-02-20 23:36:23.811000+00:00
33348           E10       1000.0 2026-02-20 23:36:23.811000+00:00
33461           E10        138.0 2026-02-21 00:41:04.773000+00:00
33460            E5        124.0 2026-02-21 00:41:04.773000+00:00
33474            E5       1000.0 2026-02-21 01:44:02.737000+00:00
33475           E10       1000.0 2026-02-21 01:44:02.737000+00:00
33507            E5        124.0 2026-02-21 04:57:17.294000+00:00
33752            E5       1000.0 2026-02-21 09:12:03.486000+00:00
33753           E10        138.0 2026-02-21 09:12:03.486000+00:00
33843           E10       1000.0 2026-02-21 10:52:03.488000+00:00
33964            E5        124.0 2026-02-21 20:36:10.612000+00:00
34059            E5       1000.0 2026-02-21 22:44:46.738000+00:00
44379           E10        999.9 2026-02-22 00:44:11.332000+00:00
44378            E5        999.9 2026-02-22 00:44:11.332000+00:00
34690           E10        137.9 2026-02-22 10:24:17.159000+00:00
34975           E10        999.9 2026-02-22 13:40:10.812000+00:00
34450           E10        137.9 2026-02-22 16:52:08.880000+00:00
34633            E5        123.7 2026-02-22 17:56:36.242000+00:00
34460           E10        999.9 2026-02-22 23:16:02.653000+00:00
34543           E10        137.9 2026-02-23 07:49:34.569000+00:00
54823            E5        999.9 2026-02-23 09:56:24.019000+00:00
54824           E10        999.9 2026-02-23 09:56:24.019000+00:00
55134            E5        123.7 2026-02-23 12:11:44.381000+00:00
55399            E5        999.9 2026-02-23 14:16:10.503000+00:00
56134           E10        137.9 2026-02-23 15:20:59.801000+00:00
56363           E10        999.9 2026-02-23 17:28:02.729000+00:00
56387            E5        123.7 2026-02-23 18:34:13.514000+00:00
56413            E5        999.9 2026-02-23 19:40:35.414000+00:00
56414           E10        137.9 2026-02-23 19:40:35.414000+00:00
56644           E10        999.9 2026-02-23 22:52:31.946000+00:00
56643            E5        123.7 2026-02-23 22:52:31.946000+00:00
56917           E10        137.9 2026-02-23 23:56:51.173000+00:00
56990            E5        999.9 2026-02-24 01:02:40.593000+00:00
56991           E10        999.9 2026-02-24 01:02:40.593000+00:00
56997            E5        123.7 2026-02-24 02:08:07.196000+00:00
56998           E10        137.9 2026-02-24 02:08:07.196000+00:00
57066            E5        999.9 2026-02-24 06:24:26.774000+00:00
57130            E5        123.7 2026-02-24 07:29:24.843000+00:00
57248            E5        999.9 2026-02-24 08:32:33.163000+00:00
57366           E10        999.9 2026-02-24 09:41:18.520000+00:00
57568            E5        123.7 2026-02-24 10:44:09.778000+00:00
57569           E10        137.9 2026-02-24 10:44:09.778000+00:00
57709            E5        999.9 2026-02-24 11:49:15.912000+00:00
57982           E10        999.9 2026-02-24 13:58:21.251000+00:00
58689            E5        123.7 2026-02-24 16:08:24.956000+00:00
58765           E10        137.9 2026-02-24 17:13:57.367000+00:00
59018            E5        999.9 2026-02-24 22:36:02.762000+00:00
59340            E5        123.7 2026-02-25 08:18:11.801000+00:00
59838            E5        999.9 2026-02-25 11:29:01.755000+00:00
59932            E5        123.7 2026-02-25 12:34:08.154000+00:00
60056            E5        999.9 2026-02-25 13:36:12.914000+00:00
60057           E10        999.9 2026-02-25 13:36:12.914000+00:00
60195           E10        137.9 2026-02-25 14:40:42.801000+00:00
60432           E10        999.9 2026-02-25 15:44:09.095000+00:00
60482           E10        137.9 2026-02-25 16:48:03.139000+00:00
60595            E5        123.7 2026-02-25 21:04:13.175000+00:00
60725           E10        999.9 2026-02-25 22:08:09.365000+00:00
60859            E5        999.9 2026-02-25 23:12:14.358000+00:00
60996           E10        137.9 2026-02-26 00:16:25.174000+00:00
61013           E10        999.9 2026-02-26 01:20:51.654000+00:00
61037            E5        123.7 2026-02-26 05:37:05.852000+00:00
61110            E5        999.9 2026-02-26 07:44:37.908000+00:00
61111           E10        137.9 2026-02-26 07:44:37.908000+00:00
61225           E10        999.9 2026-02-26 08:49:14.930000+00:00
61274            E5        123.7 2026-02-26 09:52:10.352000+00:00
61398            E5        999.9 2026-02-26 10:56:03.126000+00:00
61399           E10        137.9 2026-02-26 10:56:03.126000+00:00
61684           E10        999.9 2026-02-26 13:06:13.788000+00:00
61773           E10        137.9 2026-02-26 14:08:22.294000+00:00
62323           E10        999.9 2026-02-26 16:16:40.532000+00:00
62376            E5        123.7 2026-02-26 17:20:13.644000+00:00
62420           E10        137.9 2026-02-26 19:28:48.012000+00:00
62419            E5        999.9 2026-02-26 19:28:48.012000+00:00
62617           E10        999.9 2026-02-26 22:41:04.351000+00:00
62708            E5        123.7 2026-02-26 23:44:09.759000+00:00
62709           E10        137.9 2026-02-26 23:44:09.759000+00:00
62843            E5        999.9 2026-02-27 06:09:17.467000+00:00
62844           E10        999.9 2026-02-27 06:09:17.467000+00:00
62959           E10        137.9 2026-02-27 08:16:28.055000+00:00
63011            E5        123.7 2026-02-27 09:21:43.898000+00:00
63094           E10        999.9 2026-02-27 10:24:26.185000+00:00
63353           E10        137.9 2026-02-27 11:28:54.532000+00:00
64181            E5        999.9 2026-02-27 13:36:24.644000+00:00
64413           E10        999.9 2026-02-27 14:41:09.409000+00:00
64551           E10        137.9 2026-02-27 15:48:29.465000+00:00
64635           E10        999.9 2026-02-27 17:56:15.430000+00:00
64994            E5        123.7 2026-02-27 23:16:03.253000+00:00
64995           E10        137.9 2026-02-27 23:16:03.253000+00:00
65331            E5        999.9 2026-02-28 07:48:03.610000+00:00
65399            E5        123.7 2026-02-28 08:52:20.767000+00:00
65400           E10        999.9 2026-02-28 08:52:20.767000+00:00
65604           E10        137.9 2026-02-28 09:57:11.344000+00:00
65745            E5        999.9 2026-02-28 12:05:56.862000+00:00
65746           E10        999.9 2026-02-28 12:05:56.862000+00:00
65784            E5        123.7 2026-02-28 13:08:39.966000+00:00
65785           E10        137.9 2026-02-28 13:08:39.966000+00:00
65808            E5        999.9 2026-02-28 14:12:03.240000+00:00
65809           E10        999.9 2026-02-28 14:12:03.240000+00:00
65819           E10        137.9 2026-02-28 15:16:21.102000+00:00
65841           E10        999.9 2026-02-28 16:20:03.371000+00:00
65840            E5        123.7 2026-02-28 16:20:03.371000+00:00
65856            E5        999.9 2026-02-28 18:29:36.382000+00:00
65857           E10        137.9 2026-02-28 18:29:36.382000+00:00
66134            E5        123.7 2026-02-28 22:44:33.107000+00:00
66160           E10        999.9 2026-02-28 23:48:51.903000+00:00
66221           E10        137.9 2026-03-01 06:16:28.374000+00:00
67364            E5        999.9 2026-03-01 07:21:01.995000+00:00
67772           E10        999.9 2026-03-01 08:24:12.152000+00:00
67851           E10        137.9 2026-03-01 09:28:32.775000+00:00
67908            E5        123.7 2026-03-01 10:33:15.776000+00:00
67909           E10        999.9 2026-03-01 10:33:15.776000+00:00
68003           E10        137.9 2026-03-01 11:36:43.998000+00:00
68002            E5        999.9 2026-03-01 11:36:43.998000+00:00
68164            E5        123.7 2026-03-01 13:45:26.131000+00:00
68165           E10        999.9 2026-03-01 13:45:26.131000+00:00
68263           E10        137.9 2026-03-01 18:02:00.970000+00:00
68377            E5        999.9 2026-03-01 21:13:19.171000+00:00
68378           E10        999.9 2026-03-01 21:13:19.171000+00:00
68491           E10        137.9 2026-03-02 00:24:03.606000+00:00
68687            E5        123.7 2026-03-02 07:56:04.122000+00:00
68688           E10        999.9 2026-03-02 07:56:04.122000+00:00
68823            E5        999.9 2026-03-02 09:03:21.758000+00:00
68824           E10        137.9 2026-03-02 09:03:21.758000+00:00
70268           E10        999.9 2026-03-02 12:24:40.001000+00:00
70511           E10        137.9 2026-03-02 13:28:33.262000+00:00
70677           E10        999.9 2026-03-02 14:32:44.662000+00:00
70676            E5        123.7 2026-03-02 14:32:44.662000+00:00
71033           E10        137.9 2026-03-02 15:36:11.764000+00:00
71787            E5        999.9 2026-03-02 16:41:43.658000+00:00
72536            E5        123.7 2026-03-02 17:44:16.480000+00:00
72631           E10        999.9 2026-03-02 18:49:40.196000+00:00
72668            E5        999.9 2026-03-02 19:52:03.367000+00:00
73841            E5        123.7 2026-03-02 23:08:10.196000+00:00
74847           E10        137.9 2026-03-03 00:12:36.368000+00:00
75913            E5        999.9 2026-03-03 06:53:59.007000+00:00
75914           E10        999.9 2026-03-03 06:53:59.007000+00:00
76188            E5        123.7 2026-03-03 07:57:57.973000+00:00
76189           E10        137.9 2026-03-03 07:57:57.973000+00:00
78014           E10        999.9 2026-03-03 11:09:58.987000+00:00
78762           E10        137.9 2026-03-03 12:12:28.085000+00:00
78761            E5        999.9 2026-03-03 12:12:28.085000+00:00
79396            E5        123.7 2026-03-03 13:19:04.380000+00:00
79965            E5        999.9 2026-03-03 14:20:35.175000+00:00
79966           E10        999.9 2026-03-03 14:20:35.175000+00:00
81029           E10        137.9 2026-03-03 15:25:04.269000+00:00
82253            E5        123.7 2026-03-03 16:29:19.387000+00:00
84659            E5        999.9 2026-03-03 19:44:44.168000+00:00
86562           E10        999.9 2026-03-04 02:48:08.333000+00:00
86678            E5        123.7 2026-03-04 06:42:01.622000+00:00
86679           E10        137.9 2026-03-04 06:42:01.622000+00:00
87184           E10        999.9 2026-03-04 09:16:44.953000+00:00
88224           E10        137.9 2026-03-04 10:31:45.682000+00:00
88769            E5        999.9 2026-03-04 12:35:01.916000+00:00
89857           E10        999.9 2026-03-04 13:38:45.776000+00:00
90707            E5        123.7 2026-03-04 14:49:20.714000+00:00
93841            E5        999.9 2026-03-04 18:14:34.676000+00:00
93896           E10        137.9 2026-03-04 19:16:02.351000+00:00
94017            E5        123.7 2026-03-04 20:20:14.849000+00:00
94018           E10        999.9 2026-03-04 20:20:14.849000+00:00
94137            E5        999.9 2026-03-04 21:24:30.255000+00:00
94138           E10        137.9 2026-03-04 21:24:30.255000+00:00
94427            E5        123.7 2026-03-04 23:32:51.291000+00:00
94428           E10        999.9 2026-03-04 23:32:51.291000+00:00
94999            E5        999.9 2026-03-05 00:36:01.434000+00:00
95000           E10        137.9 2026-03-05 00:36:01.434000+00:00
95474           E10        999.9 2026-03-05 07:00:07.491000+00:00
95473            E5        123.7 2026-03-05 07:00:07.491000+00:00
95627            E5        999.9 2026-03-05 08:04:34.829000+00:00
95628           E10        137.9 2026-03-05 08:04:34.829000+00:00
95948            E5        123.7 2026-03-05 09:08:25.864000+00:00
95949           E10        999.9 2026-03-05 09:08:25.864000+00:00
96825            E5        999.9 2026-03-05 10:13:09.040000+00:00
99731           E10        137.9 2026-03-05 13:24:52.273000+00:00
101269           E5        123.7 2026-03-05 14:28:16.725000+00:00
102264          E10        999.9 2026-03-05 15:32:01.573000+00:00
102984          E10        137.9 2026-03-05 16:36:01.595000+00:00
103803          E10        999.9 2026-03-05 17:40:11.937000+00:00
103802           E5        999.9 2026-03-05 17:40:11.937000+00:00
103934           E5        123.7 2026-03-05 19:48:16.909000+00:00
105788          E10        137.9 2026-03-06 04:20:01.425000+00:00
105787           E5        999.9 2026-03-06 04:20:01.425000+00:00
106095          E10        999.9 2026-03-06 07:32:01.730000+00:00
106254           E5        123.7 2026-03-06 08:36:11.059000+00:00
106255          E10        137.9 2026-03-06 08:36:11.059000+00:00
107645          E10        999.9 2026-03-06 10:44:06.586000+00:00
108323           E5        999.9 2026-03-06 11:48:26.097000+00:00
108324          E10        137.9 2026-03-06 11:48:26.097000+00:00
109658           E5        123.7 2026-03-06 12:52:01.712000+00:00
110461           E5        999.9 2026-03-06 13:56:32.304000+00:00
110462          E10        999.9 2026-03-06 13:56:32.304000+00:00
111374           E5        123.7 2026-03-06 15:00:13.102000+00:00
112466           E5        999.9 2026-03-06 16:04:16.457000+00:00
112467          E10        137.9 2026-03-06 16:04:16.457000+00:00
113138          E10        999.9 2026-03-06 17:08:01.438000+00:00
113530           E5        123.7 2026-03-06 18:12:06.686000+00:00
113918           E5        999.9 2026-03-06 21:24:01.529000+00:00
113919          E10        137.9 2026-03-06 21:24:01.529000+00:00
116112           E5        123.7 2026-03-07 07:00:07.824000+00:00
116113          E10        999.9 2026-03-07 07:00:07.824000+00:00
116277           E5        999.9 2026-03-07 08:04:01.397000+00:00
116278          E10        137.9 2026-03-07 08:04:01.397000+00:00
116455           E5        123.7 2026-03-07 09:08:01.455000+00:00
117598          E10        999.9 2026-03-07 11:16:01.349000+00:00
117935           E5        999.9 2026-03-07 12:20:01.472000+00:00
119881          E10        137.9 2026-03-07 15:32:01.541000+00:00
119880           E5        123.7 2026-03-07 15:32:01.541000+00:00
120068           E5        999.9 2026-03-07 18:42:45.837000+00:00
121701          E10        999.9 2026-03-08 09:36:46.121000+00:00
122685           E5        123.7 2026-03-08 13:52:01.504000+00:00
122955          E10        137.9 2026-03-08 17:04:01.548000+00:00
123564           E5        999.9 2026-03-08 22:25:16.255000+00:00
123565          E10        999.9 2026-03-08 22:25:16.255000+00:00
123946           E5        123.7 2026-03-08 23:29:15.359000+00:00
123947          E10        137.9 2026-03-08 23:29:15.359000+00:00
124674           E5        999.9 2026-03-09 08:00:05.364000+00:00
124675          E10        999.9 2026-03-09 08:00:05.364000+00:00
125411           E5        123.7 2026-03-09 10:08:27.076000+00:00
125412          E10        137.9 2026-03-09 10:08:27.076000+00:00
129425          E10        999.9 2026-03-09 12:16:10.977000+00:00
133377          E10        137.9 2026-03-09 16:33:12.530000+00:00
133376           E5        999.9 2026-03-09 16:33:12.530000+00:00
133689          E10        999.9 2026-03-09 17:36:01.574000+00:00
134031           E5        123.7 2026-03-09 20:49:06.398000+00:00
138507           E5        999.9 2026-03-10 09:36:07.569000+00:00
138508          E10        137.9 2026-03-10 09:36:07.569000+00:00
139477           E5        123.7 2026-03-10 10:40:20.108000+00:00
141589           E5        999.9 2026-03-10 12:48:23.181000+00:00
142011           E5        123.7 2026-03-10 13:52:01.883000+00:00
142525           E5        999.9 2026-03-10 14:56:01.506000+00:00
143122          E10        999.9 2026-03-10 16:00:02.412000+00:00
143482          E10        137.9 2026-03-10 17:04:01.472000+00:00
145443           E5        123.7 2026-03-10 22:25:06.795000+00:00
145444          E10        999.9 2026-03-10 22:25:06.795000+00:00
146343          E10        137.9 2026-03-10 23:28:49.073000+00:00
146342           E5        999.9 2026-03-10 23:28:49.073000+00:00
147168           E5        123.7 2026-03-11 00:32:07.454000+00:00
147169          E10        999.9 2026-03-11 00:32:07.454000+00:00
147195          E10        137.9 2026-03-11 01:36:16.833000+00:00
147208           E5        999.9 2026-03-11 02:40:01.445000+00:00
147209          E10        999.9 2026-03-11 02:40:01.445000+00:00

it seems that price are not random garbage . they are alternative 1000/999 and perfectly normal price 123penny and 137 penny . sometime s within minutes of each other . and at the end of data at march 16 and march 20 suddendly new brand fuel type appears B7_STANDARD with perfect price .